### ISSUE TITLE
{BUG} Mod Items appear in every tab in creative

### ISSUE THREAD

**Issue by Cirrus-Updraft** [WhoCraft/WhoCosmetics#11]
I'm not exactly sure the issue, but the items of the mod appear in every creative tab

**Comment by Jeryn99** [comment]
Forge? Fabric? Minecraft Version?

**Comment by Cirrus-Updraft** [comment]
1.20.1 Forge, Right, Sorry about missing those details

**Comment by Jeryn99** [comment]
Fixed, wait for next version
