### ISSUE TITLE
{BUG. Crash Reports included} WhoCosmetics armor items incompatible with Regeneration mod, causes game to crash

### ISSUE THREAD

**Issue by TheLoneCrafter2017** [WhoCraft/WhoCosmetics#12]
Tested on Fabric, the title pretty much says it all. If you equip almost any of the clothing/armor (for some reason the top hat is fine) in WhoCosmetics while the Regeneration mod is also installed, it causes the game to crash. I've attached a screenshot of the error generated by the Output log and two .txt Crash Reports created via trying to equip the 6th Doctor's coat and the 5th Doctor's cricket jacket.

[crash-2024-06-28_13.27.48-client.txt](https://github.com/user-attachments/files/16060173/crash-2024-06-28_13.27.48-client.txt)
[crash-2024-06-28_13.23.59-client.txt](https://github.com/user-attachments/files/16060174/crash-2024-06-28_13.23.59-client.txt)
![image](https://github.com/Jeryn99/WhoCosmetics/assets/27866785/abfad53c-fe53-443b-8b26-54f0132d320b)

Thank you for your time :)

**Comment by Jeryn99** [comment]
Still trying to pinpoint the issue in this one, please bare with me

**Comment by KiloTheNeko** [comment]
[crash-2024-12-25_20.50.35-client.txt](https://github.com/user-attachments/files/18247073/crash-2024-12-25_20.50.35-client.txt)
adding my crashlog

**Comment by Jeryn99** [comment]
All Fixed now
