### ISSUE TITLE
{BUG. Screenshots included} Victorian Monitor missing textures. Can literally see right through it. 

### ISSUE THREAD

**Issue by TheLoneCrafter2017** [WhoCraft/WhoCosmetics#13]
Again, the title pretty much says it all. There is a slight texture error with the Victorian monitor where it's missing part of its textures on the front and back, but rather than just the traditional pink and black squares, the areas missing them are completely transparent. 
![image](https://github.com/Jeryn99/WhoCosmetics/assets/27866785/cd6abd05-4a28-4084-9844-31edd74b988d)
![image](https://github.com/Jeryn99/WhoCosmetics/assets/27866785/d0cb701e-b303-4026-96ae-14e82afc6c5a)

This was tested on Fabric, thank you for your time :)

**Comment by JWBstuhr** [comment]
This is a Sodium compatibility issue (tested) due to culling. This resource pack I created adjusts the model to avoid it.
[Victorian Monitor Fix.zip](https://github.com/user-attachments/files/16402277/Victorian.Monitor.Fix.zip)

**Comment by Jeryn99** [comment]
Consider it fixed! Thank you @JWBstuhr 

![2024-08-11_12 05 21](https://github.com/user-attachments/assets/4e553eb0-a3f8-4e95-bb78-c8ad56753903)
