### ISSUE TITLE
Coral Chair does not work... again

### ISSUE THREAD

**Issue by IvanDPhantom** [WhoCraft/WhoCosmetics#15]
So in the new 1.20.1 update, the coral chair now freezes me when I sat on it, even when I break it it keeps me stuck and only stops when I quit and rejoined the game.

I saw that it has happened before on 1.19.2 and it has happened again, please fix it.

Though while I'm here, I also want to mention that the tube light no longer works as a light source, and the 8th Doctor's Monitor doesn't connect to Tardis Refined's console like in 1.19.2, (Though I assume its because of the new updated way it is so if its too much of a hassle no need to fix it, it can be just decoration.)

**Comment by Jeryn99** [comment]
``So in the new 1.20.1 update, the coral chair now freezes me when I sat on it, even when I break it it keeps me stuck and only stops when I quit and rejoined the game.``
i hate furniture


``Though while I'm here, I also want to mention that the tube light no longer works as a light source, and the 8th Doctor's Monitor doesn't connect to Tardis Refined's console like in 1.19.2, (Though I assume its because of the new updated way it is so if its too much of a hassle no need to fix it, it can be just decoration.)``

I think I ported WhoCosmetics before we ported TR so I dropped it so I could get a update out - it will eventually come back

**Comment by Jeryn99** [comment]
I have fixed the tubelight and the Tardis Refined stuff but I am perplexed by the chair as I cannot re-create it

Is this on a server?

**Comment by IvanDPhantom** [comment]
> I have fixed the tubelight and the Tardis Refined stuff but I am perplexed by the chair as I cannot re-create it
> 
> Is this on a server?

Nope, it's on a single player world in 1.20.1, on Forge, I forgot to add that.

**Comment by Jeryn99** [comment]
I once again, hate furniture

Does it happen on the new released version?

**Comment by IvanDPhantom** [comment]
Multiple times yes, unfortunately. I only got to sit on it normally once, and that was after the game crashed.

**Comment by Jeryn99** [comment]
Interesting, I will look into it some more - could be forge specific

**Comment by Jeryn99** [comment]
Tested forge, seems fine? Are you sure you are running 2.0.7?

**Comment by IvanDPhantom** [comment]
> Tested forge, seems fine? Are you sure you are running 2.0.7?

Oh sorry, it just updated for me.

Edit: NVM A new problem has arised for me.

I tried from Modrinth but it won't work I'll send it in the next comment

**Comment by IvanDPhantom** [comment]
![Uploading 20240811_213432.jpg…]()

**Comment by IvanDPhantom** [comment]
![Uploading 20240811_213432.jpg…]()

**Comment by IvanDPhantom** [comment]
![Uploading 17233869804567594037070086555322.jpg…]()

**Comment by IvanDPhantom** [comment]
HOW DO YOU! Alright! You know what, it says it's not a Valid Mod File.

Sorry I screamed btw, pictures are hard to paste

**Comment by Jeryn99** [comment]
Ah I think I might know why, could I ask that you try this?

https://craig.software/mcmeta_forge-1.20.1-whocosmetics-2.0.7-forge.jar


With Github, sometimes you are better off using the file explorer for images

**Comment by IvanDPhantom** [comment]
It works! Thanks man, this issue is now officially closed

**Comment by IvanDPhantom** [comment]
Thanks man it works, though I hope it'll soon replace the other files, but in any case the issue is complete

**Comment by Jeryn99** [comment]
😎 

Updated them, may take a while for CurseForge to realize but Modrinth is ready to go
