### ISSUE TITLE
Rainbow Jaket....

### ISSUE THREAD

**Issue by IvanDPhantom** [WhoCraft/WhoCosmetics#16]
So I found 2 new issues, one is the classic door has a block in the door way and the door can be seen through (Though I think the 1.19.2 version had the same problem and if its too hard to fix ok.)

But the main issue: The rainbow jacket (6th Doctor clothes) is invisible, when placed on an armor stand or wearing it, it cant be seen.

SO far that's the only issue I have found again.

If you can please fix this

**Comment by Jeryn99** [comment]
Consider it fixed!

![2024-08-11_12 03 06](https://github.com/user-attachments/assets/93df4505-8492-4800-9aaa-1fd59dd0b41d)

**Comment by IvanDPhantom** [comment]
All right! Can't wait to have terrible sense of fashion once again!
