### ISSUE TITLE
Classic Doors have no collision behavior

### ISSUE THREAD

**Issue by EnderTrekkie** [WhoCraft/WhoCosmetics#17]
The classic doors block plays an animation for opening and closing, but of the 6 blocks it takes up, 5 can be walked through whether the door is open or closed (the block that represents the whole door is the only block with collision and it doesn't update when opened or closed)
I would have expected the door to behave somewhat the bulk head doors from Tardis Refined, where barrier blocks fill in the remaining area, and the block itself switches between pass-through and solid.

**Comment by Jeryn99** [comment]
Consider it fixed!

![2024-08-11_11 18 28](https://github.com/user-attachments/assets/1e068c26-ec91-4c94-87f3-1dc2ae486bac)

**Comment by IvanDPhantom** [comment]
> Consider it fixed!
> 
> ![2024-08-11_11 18 28](https://private-user-images.githubusercontent.com/36424503/356869093-1e068c26-ec91-4c94-87f3-1dc2ae486bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Mzg2MDAsIm5iZiI6MTcyMzQzODMwMCwicGF0aCI6Ii8zNjQyNDUwMy8zNTY4NjkwOTMtMWUwNjhjMjYtZWM5MS00Yzk0LTg3ZjMtMWRjMmFlNDg2YmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA0NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OGZkOTA4M2E4MmE2ZjQ3YWY1YjdhNjJiYmM1MjUxNTgyNGYwZWY3NjI4NTE5ZDk0YzljN2FkMTQzODZjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AoU3otPNFuPFZ58Wp64V5KzeTe8C3YC1gTSVjFPqvwU)

Is it not able to fit 2 blocks? It takes up 3 spaces as Ive seen.

**Comment by Jeryn99** [comment]
> > Consider it fixed!
> > ![2024-08-11_11 18 28](https://private-user-images.githubusercontent.com/36424503/356869093-1e068c26-ec91-4c94-87f3-1dc2ae486bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Mzg2MDAsIm5iZiI6MTcyMzQzODMwMCwicGF0aCI6Ii8zNjQyNDUwMy8zNTY4NjkwOTMtMWUwNjhjMjYtZWM5MS00Yzk0LTg3ZjMtMWRjMmFlNDg2YmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA0NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OGZkOTA4M2E4MmE2ZjQ3YWY1YjdhNjJiYmM1MjUxNTgyNGYwZWY3NjI4NTE5ZDk0YzljN2FkMTQzODZjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AoU3otPNFuPFZ58Wp64V5KzeTe8C3YC1gTSVjFPqvwU)
> 
> Is it not able to fit 2 blocks? It takes up 3 spaces as Ive seen.

Actually it only takes up 2x1 (collision wise), the rendering takes up the rest

**Comment by IvanDPhantom** [comment]
> > > Consider it fixed!
> > > ![2024-08-11_11 18 28](https://private-user-images.githubusercontent.com/36424503/356869093-1e068c26-ec91-4c94-87f3-1dc2ae486bac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Mzg2MDAsIm5iZiI6MTcyMzQzODMwMCwicGF0aCI6Ii8zNjQyNDUwMy8zNTY4NjkwOTMtMWUwNjhjMjYtZWM5MS00Yzk0LTg3ZjMtMWRjMmFlNDg2YmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA0NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OGZkOTA4M2E4MmE2ZjQ3YWY1YjdhNjJiYmM1MjUxNTgyNGYwZWY3NjI4NTE5ZDk0YzljN2FkMTQzODZjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AoU3otPNFuPFZ58Wp64V5KzeTe8C3YC1gTSVjFPqvwU)
> > 
> > 
> > Is it not able to fit 2 blocks? It takes up 3 spaces as Ive seen.
> 
> Actually it only takes up 2x1 (collision wise), the rendering takes up the rest

Yeah but its no longer fully 6X2 huh? Its hard to build it with the roundels... Will it be fixed soon or will it stay lile that?

**Comment by Jeryn99** [comment]
I'm not actually sure what you want me to change - I made it act the exact same as the Tardis Refined Interior doors
I know you used the bulkhead as a example, but it seems super unnecessary

**Comment by IvanDPhantom** [comment]
Its just I dont want it to be like the Bulk Head Doors, and line up correctly with the roundels...

But look if its too much trouble I understand

And if you dont understand, I mean try making a doorway with the roundels, you'll see what I mean
