### ISSUE TITLE
Wearing the fez or bowtie causes fog(and in some cases clouds) to be colored the same color as the fez/bowtie

### ISSUE THREAD

**Issue by DaPuffer** [WhoCraft/WhoCosmetics#18]
![2024-10-28_00 39 05](https://github.com/user-attachments/assets/cbfa3f46-0115-4968-b521-44f8338bb1ad)
![2024-10-28_00 39 07](https://github.com/user-attachments/assets/4c1381b6-a80d-44b6-970c-29cfe604add3)
![2024-10-28_00 42 15](https://github.com/user-attachments/assets/ecb97b70-038e-4661-8b1c-b2f9aa2a6680)

**Comment by Jeryn99** [comment]
That’s amazing but you need to actually provide me details…Mod version? Minecraft version? Mod loader? Mod loader version?

**Comment by DaPuffer** [comment]
sorry,forgot about it.
Forge 47.3.0, Mc 1.20.1, mod version 2.0.7
