### ISSUE TITLE
Item rendering in GUI

### ISSUE THREAD

**Issue by zelotbe** [WhoCraft/WhoCosmetics#2]
Hi,

Currently using the latest version of WhoCosmetics (1.0.1).
When I'm in my creative inventory only a few are rendered. The ModTab icons seem to be missing as well.
You're still able to take the items and equip them.
No errors what so ever in the latest.log 

![image](https://user-images.githubusercontent.com/19783738/92762187-a196a280-f392-11ea-9dbb-e3656c3b0549.png)
![image](https://user-images.githubusercontent.com/19783738/92762224-ac513780-f392-11ea-84f0-9be6455e48f5.png)

Mods installed:

> Refined Storage (by raoulvdberge)
> Packed Up (Backpacks) (by SuperMartijn642)
> New TARDIS Mod (by spectre0987)
> FTB Backups (by LatvianModder)
> Better Crates (by TheTestMod)
> Star Wars - Galaxy's Edge (by Honeyluck)
> Doctor Who - WhoCosmetics (by Swirtzly)
> Corail Tombstone (by Corail_31)
> The Midnight (by cipher_zero_x)
> Tool Belt (by gigaherz)
> Silent's Mechanisms (by SilentChaos512)
> Building Gadgets (by Direwolf20)
> Just Enough Items (JEI) (by mezz)
> Engineer's Decor (by wilechaote)
> Doctor Who - Regeneration (by Swirtzly)
> Create (by simibubi)
> Silent Lib (by SilentChaos512)
> Cosmetic Armor Reworked (by LainMI)
> Immersive Engineering (by BluSunrize)
> Mining Gadgets (by Direwolf20)

Forge version: 28.2.23

Thanks in advance 😅 ,
Zel

**Comment by Jeryn99** [comment]
Fixed! 

https://www.curseforge.com/minecraft/mc-mods/doctor-who-whocosmetics/files/3057931
