### ISSUE TITLE
Coral chair cannot be sat on

### ISSUE THREAD

**Issue by MCraftBoatBloke** [WhoCraft/WhoCosmetics#6]
MC Version: 1.19.2
Fabric Version: 0.14.10
Mod Version: 41.0.3

When right-clicking the "Coral Chair" from any direction almost every time (it has worked for me once out of maybe 30 tests), you do not sit down and your screen often shakes from left to right. You are unable to move your mouse any direction other than up and down and even if you break the chair this remains. The only way to stop that that I have discovered, is teleporting anywhere with commands.

**Comment by Jeryn99** [comment]
This is already fixed

**Comment by MCraftBoatBloke** [comment]
My bad, obviously missed that while reading through. I assume it's going to be fixed in a later update along with some other fixes as I am using the latest version.

**Comment by Jeryn99** [comment]
Later update yeah :)
