### ISSUE TITLE
[Bug} Ace's bat recipe conflict

### ISSUE THREAD

**Issue by AlienXtream** [WhoCraft/WhoCosmetics#7]
as per request sir
![image](https://user-images.githubusercontent.com/12606809/212878178-d028f1b2-9e50-462c-b891-bc41ee7c59cb.png)

**Comment by Jeryn99** [comment]
Consider it fixed!

![image](https://github.com/user-attachments/assets/e72c43a1-9f46-414f-a645-843eb1ec2112)
